# Vouchsafe is open source under the Apache License 2.0 — free for any use,
# including commercial. If you find it useful, the most valuable support is
# a GitHub star, sharing what you build with it, or contributing back via
# pull request or issue.

custom: ["https://github.com/kgovind-coder/vouchsafe#license"]
